[parity]
chain = "network/dev.json"
light = false

[account]
unlock = ["0x7ab1a34dEb3209a1d6Fd57Ae5f2f81E857bc5ba1"]
password = ["/Users/mroon/Documents/projects/sharecharge-contracts/network/pwd"]

[network]
port = 30303
warp = true

[rpc]
disable = false
port = 8545
interface = "local"
cors = ["*"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["*"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[ipc]
disable = false
path = "network/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub"]

[secretstore]
disable = false
nodes = []
http_interface = "local"
http_port = 8082
interface = "local"
port = 8083
path = "network/keys"

[ipfs]
enable = false
port = 5001
interface = "local"
cors = []
hosts = ["none"]

[mining]
author = "0x7ab1a34dEb3209a1d6Fd57Ae5f2f81E857bc5ba1"
engine_signer = "0x7ab1a34dEb3209a1d6Fd57Ae5f2f81E857bc5ba1"
force_sealing = true

[misc]
color = true
